name: Secure DevSecOps Pipeline 
on: 
 push:
  branches:
   - master
   - main
  workflow_dispatch:
 
jobs: 
build_and_package:
 name: BUILD_JOB
 if: github.ref == 'refs/heads/main' && github.event_name == 'push'
 runs-on: ubuntu-slim
 permissions:
   actions: read
   contents: read
   security-events: write 
   
 steps: 
      - name: Checkout Code 
        uses: actions/checkout@v7 
 
      - name: Cache Dependencies 
        uses: actions/cache@v5 
        with: 
          path: ~/.npm 
          key:  ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
 
      - name: build 
        run: npm install 
 
      - name: test 
        run: npm test 
 
      - name: Artifact upload 
        uses: actions/upload-artifact@v7 
        with: 
          name: artifact-1 
          path: | 
             package* 
 
 
      - name: deploy 
        run: echo "my code is deployed" 
